<?php
/**
 * @file
 * Code for the nems_common_page feature.
 */

include_once 'nems_common_page.features.inc';

/**
 * Implements hook_enable().
 */
function nems_common_page_enable() {
  drupal_set_message(t('NEMS common page feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function nems_common_page_disable() {
  drupal_set_message(t('NEMS common page feature is now disabled on your site.'));
}
