<?php
/**
 * @file
 * Hooks executed during module installation.
 */

/**
 * Implements hook_enable().
 */
function nems_call_for_tenders_enable() {
  drupal_set_message(t('NEMS Call For Tenders feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function nems_call_for_tenders_disable() {
  drupal_set_message(t('NEMS Call For Tenders feature is now disabled on your site.'));
}