<?php
/**
 * @file
 * Code for the NEMS Events feature.
 */

include_once 'nems_events.features.inc';

/**
 * Implements hook_theme().
 */
function nems_events_theme($existing) {
  return array(
    'views_view_field__nems_events__field_nems_core_external_url_1' => array(
      'arguments' => array('view' => NULL),
      'template' => 'views-view-field--nems-events--field-nems-core-external-url-1',
      'base hook' => 'views_view_field',
      'path' => drupal_get_path('module', 'nems_events') . '/templates',
    ),
  );
}
